### ISSUE TITLE
Home location

### ISSUE THREAD

**Issue by IdefixRC** [TobiasBales/PlayuavOSD#19] opened 2016-07-04 04:43 UTC
Hi guys,

I have trouble with the Homelocation not showing up correctly based on the compiled FW here ().
While it shows ok in the map mode, the "radar" shows it is a somewhat random direction (south when it should be north etc...). I saw this is a known bug in the main branch but had hopes that it was addressed by you already Tobias.

Thanks !

**Comment by IdefixRC** [comment] 2016-07-11 14:27
Further test: the same issue pops up when using the home arrow only :-(

**Comment by TobiasBales** [comment] 2016-07-12 06:51
It seems to be related to magnotometer.
If you fly fixed wing you can set use_compass to 0 and try again.
We heard good reports so far, currently investigating what the root cause is and then will fix it.

**Comment by IdefixRC** [comment] 2016-07-12 14:31
Thanks. Looking forward to the fix (not trivial I guess given.....)

**Comment by athertop** [comment] 2016-07-19 23:47
Hey Tobi, I finally got some OSD video recorded of a flight showing the home location and current location - demonstrating the home arrow issue. The video should appear on this link one the upload is complete: https://youtu.be/zYxcN-wGDjA

I'll paste here the comments I added to that video which describe the issues demoed in the video:
Demo of PlayUAV OSD. Screen 2 shows home location (set during arming), plus current location and home arrow. I occasionally switch to Screen 1 which also shows the distance from home (but not home location).
The video was produced to demonstrate an issue with the home arrow. The arrow seems to point to a position much further North than the home location. All the while, the home distance reads correctly from the home location recorded at arming.

Also noticed the Absolute Altitude reading reads the same as the relative Alt - we are 110m above sea level here so the AA reading should be 110m more than it displays in the OSD.

Also should note that I had to restart the copter 3 times before the OSD overlay would display. Strangely, when I first started the copter up, I had forgotten to switch on the GoPro, but on switching the OSD onto the GoPro input (camera 2) I could see a flickering black screen, but in the flickers, I could see the OSD overlay, just very briefly in the flickering display (seems to suggest a sync issue), but on switching to the board camera, which was inputting a good working video feed, there was no overlay at all. For the second power-up, I had started the GoPro this time first, and could switch between good images from either the GoPro or board camera, but in each case, the OSD overlay could not be seen (and as the GoPro image was being displayed cleanly now, I.e. no flickering, the trace of the OSD previously shown in the flickering was no longer seen). The third power-up, the OSD displayed perfectly on both video feeds.

**Comment by trgFPV** [comment] 2016-08-14 15:39
The home arrow code in fix-heading is now working perfectly fine for me. However at the time I'm writing this comment Home distance is somehow broken because the home distance code was also copied over from minimosd-extra. It would be cool if other persons could test the current fix-heading code. You can get the latest fix-heading firmware from here: https://circleci.com/api/v1/project/TobiasBales/PlayuavOSD/latest/artifacts/0/$CIRCLE_ARTIFACTS/PlayuavOSD.hex?branch=fix-heading&filter=successful Make sure you have no bad compass health messages when starting your plane/quad else the home arrow will fail. There is also soe debugging information right under the home arrow which does not show up in preview.

**Comment by StewLG** [comment] 2017-03-03 06:28
There has been no issue more important to PlayUAV than this one, so I am in no rush to declare victory prematurely. That said, it has been 5 months since this significant change was committed: https://github.com/TobiasBales/PlayuavOSD/commit/1354059b41e643bdcfe8ae7142c3ee8b050657fc, and we've had no home direction bug reports from pilots flying versions later than this commit.

I move that this issue be closed. (Perhaps we need a little ceremony?)

For more details, see:
http://en.playuav.com/question/6

**Closed as completed** 2017-03-03 14:21 UTC
